#!/bin/sh

# set your quality (%) levels here
LOW=60
MED=70
HIGH=80

# set maximum widths here
SMALL=320
MEDIUM=640
LARGE=1000

# create webp images? Y or N
CREATE_WEBP=y

# don't edit below this line
clear

SRC="$1"
SRCBASE="${1%%.*}"

# Low-res
echo "Generating low resolution..."
convert "$SRC" -quality $LOW "$SRCBASE"_low.jpg

# Large
echo "Generating large images..."
convert "$SRC" -quality $HIGH -resize $LARGE "$SRCBASE"_$LARGE.jpg

# Medium
echo "Generating medium images..."
convert "$SRC" -quality $MED -resize $MEDIUM "$SRCBASE"_$MEDIUM.jpg

# Small
echo "Generating small images..."
convert "$SRC" -quality $LOW -resize $SMALL "$SRCBASE"_$SMALL.jpg

# Create WEBP Files
if [ $CREATE_WEBP == "Y" ] || [ $CREATE_WEBP == "y" ]; then
    echo "Generating webp images..."
    convert "$SRC" -quality $LOW "$SRCBASE"_low.webp
    convert "$SRC" -quality $HIGH -resize $LARGE "$SRCBASE"_$LARGE.webp
    convert "$SRC" -quality $MED -resize $MEDIUM "$SRCBASE"_$MEDIUM.webp
    convert "$SRC" -quality $LOW -resize $SMALL "$SRCBASE"_$SMALL.webp
fi

echo "Done."
exit 0